services:
  gateway:
    container_name: EventsManagementGateway
    stdin_open: true
    tty: true
    environment:
      - DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLORING=true
      - TERM=xterm-256color
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/events-management-application-dev.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ../Shared/Shared/Configuration/Json/elk-stack-settings.json:/app/config/elk-stack-settings.json:ro
    restart: always
    networks:
      - internal-docker-network

networks:
  internal-docker-network:
    external: true