services:
  notificationsapi:
    container_name: NotificationsAPI
    stdin_open: true
    tty: true
    environment:
      - DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLORING=true
      - TERM=xterm-256color
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8094
    ports:
      - "8094:8094"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ../Shared/Shared/Configuration/Json/kafka-server-settings.json:/app/config/kafka-server-settings.json:ro
      - ../Shared/Shared/Configuration/Json/grpc-connections.json:/app/config/grpc-connections.json:ro
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - internal-docker-network

  redis:
    image: redis:latest
    container_name: NotificationsAPI_RedisServer
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - internal-docker-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  internal-docker-network:
    external: true

volumes:
  redis_data: