services:
  usersapi:
    container_name: UsersAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "8080"
      - "8081"
    depends_on:
      - sqlserver
    restart: always
    networks:
      - internal-docker-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: UsersAPI_SQLServer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SA_passw0rd
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: always
    networks:
      - internal-docker-network

networks:
  internal-docker-network:
    driver: bridge

volumes:
  sql_data: