services:
  usersapi:
    container_name: UsersAPI
    stdin_open: true
    tty: true
    environment:
      - DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLORING=true
      - TERM=xterm-256color
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8091
      - ASPNETCORE_HTTPS_PORTS=8092
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/events-management-application-dev.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ../Shared/Shared/Configuration/Json/elk-stack-settings.json:/app/config/elk-stack-settings.json:ro
    depends_on:
      - sqlserver
      - redis
    restart: always
    networks:
      - internal-docker-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: UsersAPI_SQLServer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SA_passw0rd
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
    networks:
      - internal-docker-network

  redis:
    image: redis:latest
    container_name: UsersAPI_RedisServer
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - internal-docker-network

networks:
  internal-docker-network:
    external: true

volumes:
  sql_data:
  redis_data:  